name: Deployment step 1
on: 
  push:
    branches:
      - master
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test Code
        run: npm run test
      - name: Build Code
        run: npm run build
      - name: Output log
        run: echo "Deployment completed successfully"